# Generated by Django 5.0.2 on 2024-04-08 05:24

import colorfield.fields
import django.core.validators
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Навзвание')),
                ('code', models.CharField(max_length=5, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='FavoriteItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
            ],
            options={
                'verbose_name': 'Избранный Товар',
                'verbose_name_plural': 'Избранные Товары',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание Товара')),
                ('main_features', models.TextField(verbose_name='Особенности Товара')),
                ('is_new', models.BooleanField(default=True, verbose_name='Новинка')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория Товаров',
                'verbose_name_plural': 'Категории Товаров',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('image', models.ImageField(upload_to='items/')),
            ],
            options={
                'verbose_name': 'Фотографии модели  товара',
                'verbose_name_plural': 'Фотографии модели  товара',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('name_model', models.CharField(max_length=150, verbose_name='Название модела')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('discount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Модель Товара',
                'verbose_name_plural': 'Модели Товара',
                'db_table': 'item_models',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Модел Товара',
                'verbose_name_plural': 'Модели Товара',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('terms_of_payment', models.TextField(verbose_name='Условия платежа')),
                ('delivery_conditions', models.TextField(verbose_name='Условия доставки')),
                ('use_mbank', models.BooleanField(blank=True, default=False, null=True, verbose_name='Мтод Платежа (MBANK)')),
            ],
            options={
                'verbose_name': 'Платеж Товара',
                'verbose_name_plural': 'Платежы Товара',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка для доставка')),
                ('quality', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка для качество')),
                ('price_relevance', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка для актуальность цены')),
                ('advantages', models.CharField(blank=True, max_length=250, null=True, verbose_name='Преимущества')),
                ('disadvantages', models.CharField(blank=True, max_length=250, null=True, verbose_name='Недостатки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ItemSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='subcategories/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Подкатегория Товаров',
                'verbose_name_plural': 'подкатегории Товаров',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
