# Generated by Django 5.0.2 on 2024-04-08 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('order', '0002_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteitems',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='companies.company'),
        ),
        migrations.AddField(
            model_name='favoriteitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='store.item', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.itemcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.color', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.currency'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='store.item', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='itemimages',
            name='item_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.itemmodel', verbose_name='Моде Товара'),
        ),
        migrations.AddField(
            model_name='itemmodelname',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_name', to='store.item', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='item_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='store.itemmodelname'),
        ),
        migrations.AddField(
            model_name='itempayment',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='store.item', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='itemreviews',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='itemreviews',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='store.item', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='itemreviews',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.orderitems'),
        ),
        migrations.AddField(
            model_name='itemreviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='itemsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='store.itemcategory', verbose_name='Главная категория'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.itemsubcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteitems',
            unique_together={('user', 'item')},
        ),
    ]
