# Generated by Django 5.0.2 on 2024-04-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_itemviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во просмотров'),
        ),
    ]
