# Generated by Django 5.0.2 on 2024-04-29 04:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_itemviews_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemviews',
            unique_together={('user', 'item', 'ip')},
        ),
    ]
