# Generated by Django 5.0.2 on 2024-06-14 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_itemviews_unique_together_alter_itemviews_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmodelname',
            options={'managed': True, 'verbose_name': 'Типы Товара', 'verbose_name_plural': 'Типы Товара'},
        ),
        migrations.AlterModelOptions(
            name='itemviews',
            options={'verbose_name': 'Просмотр Товара', 'verbose_name_plural': 'Просмотры Товаров'},
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='item_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='store.itemmodelname', verbose_name='Тип Товара'),
        ),
    ]
