# Generated by Django 5.0.2 on 2024-06-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accountsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasword',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('company', 'Компания'), ('client', 'Клиент')], default='client', max_length=30, verbose_name='Роль'),
        ),
    ]
