# Generated by Django 5.0.2 on 2024-04-08 05:24

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=100, verbose_name='Имя Заказчика')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон Заказчика')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментария Заказчика')),
                ('status', models.CharField(choices=[('in browsing', 'в просмотре'), ('in processing', 'в процессе'), ('Done', 'Получено'), ('Reject', 'ОТКЛОНЕН')], default='in browsing', max_length=30)),
            ],
            options={
                'verbose_name': 'Заказ от клиента',
                'verbose_name_plural': 'Заказы от клиентов',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('status', models.CharField(choices=[('in browsing', 'в просмотре'), ('in processing', 'в процессе'), ('Done', 'Получено'), ('Reject', 'ОТКЛОНЕН')], default='in browsing', max_length=30)),
            ],
            options={
                'verbose_name': 'Товар Заказа',
                'verbose_name_plural': 'Товары Заказа',
            },
        ),
    ]
