# Generated by Django 5.0.2 on 2024-04-25 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
        ('store', '0005_itemviews_ip_alter_itemviews_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='item_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.itemmodel', verbose_name='Модель Товара'),
        ),
    ]
